remote_theme: riggraz/no-style-please
google-site-verification: googleac5c27a26033b05a.html

title: Riccardo's page
description: Permanently under construction. Mostly a link container. Hopefully useful.

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "<<" # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page

github:
  is_project_page: false
markdown: kramdown
kramdown:
    math_engine: mathjax

plugins:
  - jekyll-paginate
  - jekyll-sitemap
