remote_theme: riggraz/no-style-please
google-site-verification: googleac5c27a26033b05a.html

title: Riccardo's page


github:
  is_project_page: false
markdown: kramdown
kramdown:
    math_engine: mathjax

plugins:
  - jekyll-paginate
  - jekyll-sitemap
