remote_theme: riggraz/no-style-please

title: Riccardo's page
author: Riccardo Marchesin
description: Permanently under construction. Mostly a link container. Hopefully interesting.

google-site-verification: googleac5c27a26033b05a.html


github:
  is_project_page: false
markdown: kramdown
kramdown:
    math_engine: mathjax

plugins:
  - jekyll-paginate
  - jekyll-sitemap
