theme: jekyll-theme-tactile

title: TITOLOO 
description: sottotitolo.
author: Riccardo marchesin

social-network-links:
  email: "someone@example.com"
  github: r-marche
#  twitter: ''
#  youtube: ''
#  medium: yourname
#  reddit: yourname
  linkedin: j
#  stackoverflow: ""
#  snapchat: ''
#  instagram: ''
  telegram: jj
#  google-scholar: your google scholar



github:
  is_project_page: false
markdown: kramdown
kramdown:
    math_engine: mathjax

plugins:
  - jekyll-paginate
  - jekyll-sitemap
